# Generated by Django 5.1 on 2024-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=12)),
                ('before', models.IntegerField()),
                ('after', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Сплит',
                'verbose_name_plural': 'Сплиты',
                'unique_together': {('date', 'ticker')},
            },
        ),
    ]
