# Generated by Django 5.1 on 2024-10-07 17:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_currency_auto_rate_preload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('targetPrice', models.IntegerField(default=1000, verbose_name='Цель (капитал)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='lastprice',
            options={'verbose_name': 'Цена текущая', 'verbose_name_plural': 'Цены текущие'},
        ),
        migrations.CreateModel(
            name='TargetPortfolioAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ManyToManyField(to='analyzer.account')),
                ('targetPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.targetportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='TargetPortfolioValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('indexTarget', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Вес в индексе')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='Мой коэффициент')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.instrumentdata')),
                ('targetPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyzer.targetportfolio')),
            ],
        ),
    ]
