# Generated by Django 5.1 on 2024-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_targetportfolio_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetportfolio',
            name='accounts',
            field=models.ManyToManyField(to='analyzer.account'),
        ),
        migrations.DeleteModel(
            name='TargetPortfolioAccounts',
        ),
    ]
