# Generated by Django 5.1 on 2024-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_targetportfolio_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Bank name in English')),
                ('short_name', models.CharField(max_length=20, verbose_name='Краткое название')),
                ('short_name_eng', models.CharField(max_length=20, verbose_name='Short name in English')),
                ('figi', models.CharField(max_length=20, verbose_name='figi')),
                ('alias', models.CharField(max_length=20, verbose_name='Внутренний идентификатор')),
                ('show_link', models.BooleanField(default=True, verbose_name='Показывать ссылку')),
                ('url_template', models.CharField(default='', max_length=200, verbose_name='Ссылка на инструменты')),
            ],
        ),
    ]
