# Generated by Django 5.1 on 2025-01-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.AddField(
            model_name='account',
            name='bankId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.bank', verbose_name='Банк/Брокер'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Тип счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountId',
            field=models.CharField(max_length=64, unique=True, verbose_name='Идентификатор'),
        ),
    ]
